version: '3.8'

services:
  my-story-buddy-local:
    build:
      context: .
      dockerfile: Dockerfile.ec2
    container_name: my-story-buddy-local
    ports:
      - "8003:8003"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWS_REGION=us-east-1
      # AWS credentials will be provided via volume mount or environment variables
    volumes:
      # Mount AWS credentials directory (if it exists)
      - ~/.aws:/root/.aws:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M