name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Create deployment package
        run: |
          mkdir -p deployment
          cp main.py deployment/
          cp lambda_function.py deployment/ 2>/dev/null || true
          cp requirements.txt deployment/
          cp auth_routes.py deployment/
          cp auth_models.py deployment/
          cp auth_utils.py deployment/
          cp database.py deployment/
          # cp google_auth.py deployment/  # Temporarily disabled due to cryptography dependency
          cp email_service.py deployment/
          cd deployment
          
          # Use Docker to install packages in Lambda-compatible environment
          docker run --rm -v $(pwd):/var/task \
            -w /var/task \
            public.ecr.aws/lambda/python:3.9 \
            sh -c "pip install -r requirements.txt -t . --no-deps --force-reinstall && \
                   pip install -r requirements.txt -t . --force-reinstall"
          
          # Remove unnecessary files to reduce package size
          find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
          find . -type d -name "*.dist-info" -exec rm -rf {} + 2>/dev/null || true
          find . -type d -name "*.egg-info" -exec rm -rf {} + 2>/dev/null || true
          find . -name "*.pyc" -delete 2>/dev/null || true
          find . -name "*.pyo" -delete 2>/dev/null || true
          
          zip -r ../deployment.zip .

      - name: Deploy to Lambda
        run: |
          # Update function code
          aws lambda update-function-code \
            --function-name my-story-buddy \
            --zip-file fileb://deployment.zip
          
          # Verify function configuration
          aws lambda get-function \
            --function-name my-story-buddy \
            --query 'Configuration.[Runtime,Handler]' \
            --output text
          
          # Update function configuration if needed
          aws lambda update-function-configuration \
            --function-name my-story-buddy \
            --handler main.handler \
            --runtime python3.9 \
            --timeout 30 \
            --memory-size 256 