name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Create deployment package
        run: |
          mkdir -p deployment
          cp main.py deployment/
          cp lambda_function.py deployment/ 2>/dev/null || true
          cp requirements.txt deployment/
          cp auth_routes.py deployment/ 2>/dev/null || true
          cp auth_models.py deployment/ 2>/dev/null || true
          cp auth_utils.py deployment/ 2>/dev/null || true
          cp database.py deployment/ 2>/dev/null || true
          cp email_service.py deployment/ 2>/dev/null || true
          cd deployment
          pip install -r requirements.txt -t .
          # Remove unnecessary files to reduce package size
          find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
          find . -type d -name "*.dist-info" -exec rm -rf {} + 2>/dev/null || true
          find . -type d -name "*.egg-info" -exec rm -rf {} + 2>/dev/null || true
          
          zip -r ../deployment.zip .

      - name: Deploy to Lambda
        run: |
          # Update function code
          aws lambda update-function-code \
            --function-name my-story-buddy \
            --zip-file fileb://deployment.zip \
            --region us-west-2
          
          # Update function configuration  
          aws lambda update-function-configuration \
            --function-name my-story-buddy \
            --runtime python3.11 \
            --timeout 30 \
            --memory-size 512 \
            --environment Variables="{OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}}" \
            --region us-west-2 